"""Promotion proposal generator — KR-PROMOTE-PHRASEBOOK-FOUNDATION (Deliverable C).

Input: a list of :class:`ReasoningObservation` from the observer.
Output: zero or more :class:`PromotionProposal` records, each
suggesting a new phrasebook entry that would short-circuit a
cluster of recurring operator DMs.

# Pipeline

  1. Embed each observation's ``kora_response`` text via
     :func:`kora_cli.clustering.text_similarity.embed_texts`
     (lexical, $0).
  2. Cluster via greedy agglomerative similarity at
     ``cohesion_threshold`` (default 0.85).
  3. For each cluster ≥ ``min_cluster_size``:
     a. Check answer-consistency: the LARGEST sub-cluster of
        near-identical Kora answers must cover at least
        ``answer_consistency_threshold`` (default 0.75) of the
        outer cluster. Divergent-answer clusters get dropped —
        a proposed template that doesn't match Kora's actual
        behavior is worse than no proposal.
     b. Derive a candidate regex pattern from common
        tokens / phrases.
     c. Derive the reply template from the dominant Kora answer
        (or optionally synthesize via Haiku — one call per
        proposal). Defaults to "dominant answer" because it's
        $0 and forces operator review of any Haiku-synthesized
        text anyway.
     d. Mint a :class:`PromotionProposal` with confidence
        derived from cluster cohesion + answer consistency.

# Cost discipline

Lexical embedder: $0. Optional Haiku reply-template synthesis:
~$0.001 per proposal at default thresholds (5-observation
clusters with consistent answers → maybe 2-5 proposals per cycle
in realistic operator-DM volumes). Per cycle: ≤$0.005. Daily
ceiling: well within the $0.01-0.05/day target.

The bucket's STOP-ASK §4 anticipated "pattern derivation generates
pathological regexes" — we mitigate by **escaping all regex
metacharacters** in the derived pattern and emitting a simple
case-insensitive alternation of the cluster's dominant short
phrases. The phrasebook PUT endpoint's existing validator (PR #177
``phrasebook_editor.validate_entries``) will reject any malformed
regex at approve-time anyway, so the worst case is a rejected
operator approval rather than a runtime regex bomb.
"""

from __future__ import annotations

import logging
import re
import uuid
from collections import Counter
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Awaitable, Callable, Dict, List, Literal, Optional, Tuple

from kora_cli.clustering.text_similarity import (
    TextEmbedding,
    cluster_by_similarity,
    cosine_similarity,
    embed_texts,
)

from .observer import ReasoningObservation

logger = logging.getLogger(__name__)


ProposalStatus = Literal["pending", "approved", "rejected", "expired"]

# Wire-stable status values — paired with the FE constant CC#2
# adds in KR-FE-PROMOTION-REVIEW-PANEL. Update both sides together
# when extending.
PROPOSAL_STATUS_VALUES: Tuple[ProposalStatus, ...] = (
    "pending",
    "approved",
    "rejected",
    "expired",
)


# Default thresholds — kept conservative so operator isn't flooded
# with marginal proposals on day one. Operator can loosen via the
# cycle's keyword args (cron task reads from env).
DEFAULT_MIN_CLUSTER_SIZE = 5
DEFAULT_COHESION_THRESHOLD = 0.85
DEFAULT_ANSWER_CONSISTENCY_THRESHOLD = 0.75

# Sample-question cap exposed to the operator in the proposal
# review UI. Three is enough to recognize the cluster shape
# without overwhelming the panel.
SAMPLE_QUESTIONS_CAP = 3


@dataclass(frozen=True, slots=True)
class PromotionProposal:
    """Wire-stable proposal shape. Persisted as JSON by
    :mod:`.store` and surfaced via the cockpit API endpoints in
    web_server.py.
    """

    proposal_id: str
    cluster_size: int
    sample_questions: List[str]
    proposed_pattern: str
    proposed_reply_template: str
    proposed_category: str
    confidence: float
    created_at: datetime
    status: ProposalStatus
    review_notes: str = ""
    # KR-PROMOTE-PHRASEBOOK-FOUNDATION — back-references so the
    # cockpit can render the observation context that triggered
    # the proposal without re-running the cycle.
    cluster_caller_session_ids: List[str] = field(default_factory=list)
    # ``haiku_synthesized`` is True when the reply_template was
    # generated by a Haiku call; False when it's the dominant
    # cluster member verbatim. Operator approval UI can flag
    # synthesized text for extra-careful review.
    haiku_synthesized: bool = False


def _format_iso(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def proposal_to_dict(p: PromotionProposal) -> Dict[str, Any]:
    """Serialize a PromotionProposal to a JSON-safe dict for both
    audit emission and on-disk persistence."""
    out = asdict(p)
    out["created_at"] = _format_iso(p.created_at)
    return out


def proposal_from_dict(payload: Dict[str, Any]) -> PromotionProposal:
    """Rehydrate a proposal from its serialized form. Strict
    field-presence (no defaulting of required fields) so a
    malformed file surfaces loudly at load time."""
    ts_raw = payload.get("created_at", "")
    if isinstance(ts_raw, str) and ts_raw:
        if ts_raw.endswith("Z"):
            ts_raw = ts_raw[:-1] + "+00:00"
        created_at = datetime.fromisoformat(ts_raw)
        if created_at.tzinfo is None:
            created_at = created_at.replace(tzinfo=timezone.utc)
    else:
        created_at = datetime.now(timezone.utc)
    return PromotionProposal(
        proposal_id=str(payload["proposal_id"]),
        cluster_size=int(payload["cluster_size"]),
        sample_questions=list(payload.get("sample_questions") or []),
        proposed_pattern=str(payload["proposed_pattern"]),
        proposed_reply_template=str(payload["proposed_reply_template"]),
        proposed_category=str(payload["proposed_category"]),
        confidence=float(payload.get("confidence") or 0.0),
        created_at=created_at,
        status=str(payload.get("status") or "pending"),  # type: ignore[arg-type]
        review_notes=str(payload.get("review_notes") or ""),
        cluster_caller_session_ids=list(
            payload.get("cluster_caller_session_ids") or []
        ),
        haiku_synthesized=bool(payload.get("haiku_synthesized") or False),
    )


# ---------------------------------------------------------------------------
# Pattern + template + category derivation
# ---------------------------------------------------------------------------


_STOPWORDS = frozenset(
    {
        "a",
        "an",
        "and",
        "are",
        "as",
        "at",
        "be",
        "by",
        "for",
        "from",
        "i",
        "in",
        "is",
        "it",
        "of",
        "on",
        "or",
        "that",
        "the",
        "this",
        "to",
        "was",
        "what",
        "with",
        "you",
    }
)


_TOKEN_RE = re.compile(r"[A-Za-z0-9]+")


def _meaningful_tokens(text: str) -> List[str]:
    return [
        t
        for t in _TOKEN_RE.findall(text.lower())
        if t not in _STOPWORDS and len(t) >= 2
    ]


def _dominant_phrase(observations: List[ReasoningObservation]) -> str:
    """Return the longest token-substring that appears in
    ``≥ half`` the observations' RESPONSES. Used as the
    inferred-question-shape signal for pattern derivation since
    v1 ships reply-only clustering.

    Reply-shape ↔ question-shape correspondence: similar
    reasoning answers are evidence of similar reasoning inputs.
    For short DMs this proxy holds; the resulting pattern is the
    operator's responsibility to refine on approval.

    Fallback: most common 1-gram across responses.
    """
    docs = [_meaningful_tokens(o.kora_response) for o in observations]
    if not docs:
        return ""
    # Score each token by document-frequency.
    df: Counter = Counter()
    for doc in docs:
        for tok in set(doc):
            df[tok] += 1
    if not df:
        return ""
    most_common = df.most_common(1)[0][0]
    return most_common


def _derive_pattern(
    observations: List[ReasoningObservation],
) -> str:
    """Generate a conservative regex pattern from the cluster's
    common-token vocabulary. We use a simple alternation of the
    top-3 cross-observation tokens with all regex metacharacters
    escaped — pathological inputs (extension points like ``(`` or
    ``*``) can't bomb the engine at compile-time.

    The pattern is intentionally LOOSE — it's the operator's job
    to tighten it on approval if they don't like the breadth. The
    spec's STOP-ASK §4 anticipated regex pathology; we mitigate
    via escape + alternation + the editor's own validator at
    approve-time.
    """
    # Build doc-frequency over tokens in the RESPONSES (proxy for
    # question shape; v1 reply-only clustering).
    df: Counter = Counter()
    docs = [_meaningful_tokens(o.kora_response) for o in observations]
    for doc in docs:
        for tok in set(doc):
            df[tok] += 1
    if not df:
        return "(?i).*"  # operator must refine; defensive default
    top = [tok for tok, _ in df.most_common(3)]
    escaped = [re.escape(t) for t in top]
    return "(?i)(" + "|".join(escaped) + ")"


def _derive_category(
    observations: List[ReasoningObservation],
) -> str:
    """Heuristic: match keywords against the existing phrasebook's
    known categories so cockpit grouping stays consistent.

    Falls back to ``"operator_query"`` (a stable default name
    operator can rename on approval) — the phrasebook editor's
    validator accepts arbitrary non-empty category strings, so
    the fallback is always valid.
    """
    combined = " ".join(o.kora_response for o in observations).lower()
    keyword_to_category = {
        "burn": "cost_query",
        "cost": "cost_query",
        "spend": "cost_query",
        "alert": "alerts_query",
        "alerts": "alerts_query",
        "paused": "state_query",
        "pause": "state_query",
        "state": "state_query",
        "healthy": "health_query",
        "health": "health_query",
        "ticket": "tickets_query",
        "sea": "tickets_query",
    }
    for keyword, category in keyword_to_category.items():
        if re.search(rf"\b{re.escape(keyword)}\b", combined):
            return category
    return "operator_query"


def _answer_consistency_subcluster(
    observations: List[ReasoningObservation],
    *,
    threshold: float = 0.75,
) -> Tuple[List[ReasoningObservation], float]:
    """Find the largest sub-cluster of near-identical responses.

    Returns ``(dominant_subcluster, fraction_of_outer)``. When
    fraction < ``threshold`` the proposer drops the cluster (the
    cluster's questions are similar but Kora's answers diverge —
    a template would mislead).
    """
    if not observations:
        return ([], 0.0)
    n = len(observations)
    # Embed responses fresh via the synchronous helper from the
    # clustering module — avoids event-loop entanglement in this
    # sync subroutine. embed_texts is async only because of its
    # forward-compat with a Haiku-backed embedder; the lexical
    # path is microseconds and pure-CPU.
    from kora_cli.clustering.text_similarity import _compute_embedding

    embs = [
        TextEmbedding(
            text=o.kora_response,
            embedding=_compute_embedding(o.kora_response),
            cached=False,
        )
        for o in observations
    ]
    # Greedy: pick the first as seed; gather all observations with
    # cosine ≥ 0.92 (intra-answer consistency is tighter than
    # cross-cluster cohesion). Repeat with each unclaimed seed;
    # keep the largest subcluster.
    INTRA_THRESHOLD = 0.92
    best_subset: List[int] = []
    for seed_idx in range(n):
        members = [seed_idx]
        for other_idx in range(n):
            if other_idx == seed_idx:
                continue
            if (
                cosine_similarity(embs[seed_idx], embs[other_idx])
                >= INTRA_THRESHOLD
            ):
                members.append(other_idx)
        if len(members) > len(best_subset):
            best_subset = members
    fraction = len(best_subset) / n
    dominant = [observations[i] for i in best_subset]
    return (dominant, fraction)


def _dominant_response_text(
    observations: List[ReasoningObservation],
) -> str:
    """Return the most-common verbatim response (after light
    whitespace normalization). Used as the proposed reply
    template when no Haiku synthesis is requested."""
    if not observations:
        return ""
    counter: Counter = Counter(
        " ".join(o.kora_response.split()) for o in observations
    )
    return counter.most_common(1)[0][0]


# ---------------------------------------------------------------------------
# Optional Haiku-driven reply-template synthesis
# ---------------------------------------------------------------------------


ReplyTemplateSynthesizer = Callable[
    [List[ReasoningObservation]], Awaitable[Tuple[Optional[str], float]]
]


async def _default_synthesizer(
    observations: List[ReasoningObservation],
) -> Tuple[Optional[str], float]:
    """Returns ``(template, cost_usd)``. Default returns
    ``(None, 0.0)`` — caller falls back to the dominant verbatim
    response. Production wiring substitutes a Haiku-call shim;
    tests inject a deterministic stub."""
    return (None, 0.0)


async def generate_proposals(
    observations: List[ReasoningObservation],
    *,
    min_cluster_size: int = DEFAULT_MIN_CLUSTER_SIZE,
    cohesion_threshold: float = DEFAULT_COHESION_THRESHOLD,
    answer_consistency_threshold: float = (
        DEFAULT_ANSWER_CONSISTENCY_THRESHOLD
    ),
    synthesize_reply_template: Optional[ReplyTemplateSynthesizer] = None,
    now: Optional[datetime] = None,
) -> Tuple[List[PromotionProposal], float]:
    """Cluster + derive proposals. Returns
    ``(proposals, total_haiku_cost_usd)`` — caller surfaces the
    cost in the cycle log + audit.

    Args:
      observations: From :func:`observer.collect_recent_observations`.
      min_cluster_size: Drop clusters smaller than this.
      cohesion_threshold: Greedy-agglomerative similarity floor.
      answer_consistency_threshold: Fraction of cluster that must
        share a near-identical response. Below this → cluster
        dropped (template would mislead).
      synthesize_reply_template: Optional Haiku-based template
        synthesizer. ``None`` → use dominant verbatim response.
      now: Test-injectable timestamp for proposal created_at.

    Determinism: identical inputs ⇒ identical proposal_ids,
    pattern strings, and ordering (lexical embedder is
    deterministic; uuid4 is the only nondeterminism and lives
    only on the proposal_id field — extracted into ``now`` only
    if the caller wants reproducibility).
    """
    if not observations:
        return ([], 0.0)
    synth = synthesize_reply_template or _default_synthesizer
    timestamp = now or datetime.now(timezone.utc)

    embeddings = await embed_texts(
        [o.kora_response for o in observations]
    )
    clusters = cluster_by_similarity(
        embeddings, threshold=cohesion_threshold
    )

    proposals: List[PromotionProposal] = []
    total_synth_cost = 0.0

    for cluster in clusters:
        if len(cluster) < min_cluster_size:
            continue
        # Re-associate cluster embeddings back to their observations.
        # The embeddings preserve input order; we use the text-to-
        # observation mapping for lookup (texts are unique per call
        # site under normal load; collisions just fold harmlessly).
        text_to_obs: Dict[str, ReasoningObservation] = {}
        for obs in observations:
            text_to_obs.setdefault(obs.kora_response, obs)
        cluster_obs = [text_to_obs[e.text] for e in cluster if e.text in text_to_obs]
        if len(cluster_obs) < min_cluster_size:
            continue

        dominant_obs, consistency = _answer_consistency_subcluster(
            cluster_obs,
            threshold=answer_consistency_threshold,
        )
        if consistency < answer_consistency_threshold:
            logger.info(
                "[kora.promote.phrasebook.proposer] cluster size=%d "
                "rejected — answer consistency %.2f < threshold %.2f",
                len(cluster_obs),
                consistency,
                answer_consistency_threshold,
            )
            continue

        # Pattern + category from the broader cluster (more signal
        # → better pattern). Reply template from the dominant
        # sub-cluster (consistency → safer template).
        pattern = _derive_pattern(cluster_obs)
        category = _derive_category(cluster_obs)
        synthesized_template, synth_cost = await synth(dominant_obs)
        total_synth_cost += synth_cost
        if synthesized_template:
            reply_template = synthesized_template
            haiku_synth = True
        else:
            reply_template = _dominant_response_text(dominant_obs)
            haiku_synth = False

        # Cohesion proxy for confidence: average max-link sim
        # across the cluster.
        cohesion = _cluster_cohesion(cluster)
        confidence = round((cohesion + consistency) / 2.0, 4)

        sample_q: List[str] = []
        for obs in cluster_obs[:SAMPLE_QUESTIONS_CAP]:
            # v1 reply-only clustering — operator_question is
            # typically "" so we surface the response excerpt
            # instead (renamed in the cockpit panel as "what Kora
            # has been saying" so operator can recognize the
            # cluster).
            if obs.operator_question:
                sample_q.append(obs.operator_question)
            else:
                sample_q.append(obs.kora_response[:200])

        proposal = PromotionProposal(
            proposal_id=str(uuid.uuid4()),
            cluster_size=len(cluster_obs),
            sample_questions=sample_q,
            proposed_pattern=pattern,
            proposed_reply_template=reply_template,
            proposed_category=category,
            confidence=confidence,
            created_at=timestamp,
            status="pending",
            review_notes="",
            cluster_caller_session_ids=[
                o.caller_session_id for o in cluster_obs
            ],
            haiku_synthesized=haiku_synth,
        )
        proposals.append(proposal)

    # Sort newest+highest-confidence first — operator's primary
    # triage view in the cockpit panel.
    proposals.sort(key=lambda p: (-p.confidence, -p.cluster_size))
    return (proposals, total_synth_cost)


def _cluster_cohesion(cluster: List[TextEmbedding]) -> float:
    """Average max-link similarity across the cluster's members.
    Cohesion ≥ threshold is enforced at clustering time; this
    measures HOW MUCH ABOVE threshold the cluster is — useful
    confidence signal."""
    n = len(cluster)
    if n <= 1:
        return 1.0
    total = 0.0
    pairs = 0
    for i in range(n):
        for j in range(i + 1, n):
            total += cosine_similarity(cluster[i], cluster[j])
            pairs += 1
    if pairs == 0:
        return 1.0
    return total / pairs
